FROM node

WORKDIR ./app

ARG REACT_APP_CLOUD_NAME
ARG REACT_APP_CLOUD_FOLDER
ARG REACT_APP_CLOUD_PRESET

ENV REACT_APP_CLOUD_NAME $REACT_APP_CLOUD_NAME
ENV REACT_APP_CLOUD_FOLDER $REACT_APP_CLOUD_FOLDER
ENV REACT_APP_CLOUD_PRESET $REACT_APP_CLOUD_PRESET

COPY public ./public
COPY src ./src
COPY package.json package-lock.json ./

RUN npm install && npm run build

RUN npm install -g serve

ENTRYPOINT ["serve","-s","build"]

EXPOSE 5000
